# Generated by Django 4.2.6 on 2024-01-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='amount',
            new_name='sum',
        ),
    ]
